version: '2'

services:
  consul:
    image: greenpau/consul
    container_name: consul
    build: consul/
    command: /init.sh
    volumes:
      - ./consul/config:/consul/config
      - /opt/data/consul/data:/consul/data
    ports:
      - "8600:8600/udp"
      - "8300:8300"
      - "8500:8500"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
